In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [5]:
csv = pd.read_csv('/content/sample_data/california_housing_train.csv')

### Dataset cleaning

In [7]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [8]:
csv.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [11]:
csv = pd.read_csv('/data.csv', encoding='latin1')

In [12]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [14]:
csv.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [15]:
csv.dropna(inplace=True)

In [16]:
csv.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [18]:
csv.to_csv('data_clean.csv')

In [20]:
csv.to_csv('data_clean.csv', index=False)

In [28]:
from google.colab import files
files.download('data_clean.csv')

In [23]:
csv.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12-01-2010 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12-01-2010 08:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12-01-2010 08:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12-01-2010 08:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12-01-2010 08:34,1.69,13047.0,United Kingdom

In [24]:
csv.shape

(406829, 8)

In [29]:
csv.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [33]:
csv.duplicated().sum()

np.int64(5225)

In [35]:
csv.drop_duplicates(inplace=True)

In [36]:
csv.duplicated().sum()

np.int64(0)

In [37]:
csv['InvoiceDate'].dtype

dtype('O')

In [40]:
csv['InvoiceDate'] = pd.to_datetime(csv['InvoiceDate'], format='mixed')

In [41]:
csv.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [45]:
csv.head(1)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom

### 1. Dataset Overview

In [44]:
#Q1. How many rows and columns are there?
csv.shape

(401604, 8)

In [47]:
#Q2. How many unique customers, products, countries, and invoices are there?
csv[['CustomerID','StockCode','Country','InvoiceNo']].nunique()

CustomerID     4372
StockCode      3684
Country          37
InvoiceNo     22190
dtype: int64

In [65]:
csv.nunique()

InvoiceNo      22190
StockCode       3684
Description     3896
Quantity         436
InvoiceDate    20460
UnitPrice        620
CustomerID      4372
Country           37
sales           4041
dtype: int64

In [50]:
#Q3. Find summary statistics for Quantity and UnitPrice.
csv[['Quantity','UnitPrice']].describe()

            Quantity      UnitPrice
count  401604.000000  401604.000000
mean       12.183273       3.474064
std       250.283037      69.764035
min    -80995.000000       0.000000
25%         2.000000       1.250000
50%         5.000000       1.950000
75%        12.000000       3.750000
max     80995.000000   38970.000000

### 2. Create Sales Column

In [51]:
#Q4. Calculate sales for each transaction.
csv['sales']= csv['Quantity'] * csv['UnitPrice']

In [52]:
csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [53]:
#Q5. What is the total revenue?
csv['sales'].sum()

np.float64(8278519.4240000015)

In [54]:
#Q6. What is the average transaction value?
csv['sales'].mean()

np.float64(20.613637872132752)

### 3. Country Analysis

In [59]:
#Q7. Which countries generate the most revenue?
csv.groupby('Country')['sales'].sum().sort_values(ascending=False)

Country
United Kingdom          6747156.154
Netherlands              284661.540
EIRE                     250001.780
Germany                  221509.470
France                   196626.050
Australia                137009.770
Switzerland               55739.400
Spain                     54756.030
Belgium                   40910.960
Sweden                    36585.410
Japan                     35340.620
Norway                    35163.460
Portugal                  28995.760
Finland                   22326.740
Channel Islands           20076.390
Denmark                   18768.140
Italy                     16890.510
Cyprus                    12858.760
Austria                   10154.320
Singapore                  9120.390
Poland                     7213.140
Israel                     6988.400
Greece                     4710.520
Iceland                    4310.000
Canada                     3666.380
Unspecified                2660.770
Malta                      2505.470
United Arab Emirates       1902.280
USA                        1730.920
Lebanon                    1693.880
Lithuania                  1661.060
European Community         1291.750
Brazil                     1143.600
RSA                        1002.310
Czech Republic              707.720
Bahrain                     548.400
Saudi Arabia                131.170
Name: sales, dtype: float64

In [60]:
#Q8. Find the top 10 countries by revenue.
csv.groupby('Country')['sales'].sum().sort_values(ascending=False).head(10)

Country
United Kingdom    6747156.154
Netherlands        284661.540
EIRE               250001.780
Germany            221509.470
France             196626.050
Australia          137009.770
Switzerland         55739.400
Spain               54756.030
Belgium             40910.960
Sweden              36585.410
Name: sales, dtype: float64

In [63]:
#Q9. How many orders are there in each country?
csv.groupby('Country')['InvoiceNo'].nunique().sort_values(ascending=False)

Country
United Kingdom          19857
Germany                   603
France                    458
EIRE                      319
Belgium                   119
Spain                     105
Netherlands               101
Switzerland                71
Portugal                   70
Australia                  69
Italy                      55
Finland                    48
Sweden                     46
Norway                     40
Channel Islands            33
Japan                      28
Poland                     24
Denmark                    21
Cyprus                     20
Austria                    19
Singapore                  10
Malta                      10
Unspecified                 8
Iceland                     7
USA                         7
Israel                      6
Canada                      6
Greece                      6
Czech Republic              5
European Community          5
Lithuania                   4
United Arab Emirates        3
Bahrain                     2
Saudi Arabia                2
Brazil                      1
Lebanon                     1
RSA                         1
Name: InvoiceNo, dtype: int64

In [73]:
#Q10. Which are the top 10 products by revenue?
csv.groupby('Description')['sales'].sum().sort_values(ascending=False).head(10)

Description
REGENCY CAKESTAND 3 TIER              132567.70
WHITE HANGING HEART T-LIGHT HOLDER     93767.80
JUMBO BAG RED RETROSPOT                83056.52
PARTY BUNTING                          67628.43
POSTAGE                                66710.24
ASSORTED COLOUR BIRD ORNAMENT          56331.91
RABBIT NIGHT LIGHT                     51042.84
CHILLI LIGHTS                          45915.41
PAPER CHAIN KIT 50'S CHRISTMAS         41423.78
PICNIC BASKET WICKER 60 PIECES         39619.50
Name: sales, dtype: float64

In [75]:
# Q11. Which are the top 10 products by quantity sold?
csv.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS     53119
JUMBO BAG RED RETROSPOT               44963
ASSORTED COLOUR BIRD ORNAMENT         35215
WHITE HANGING HEART T-LIGHT HOLDER    34128
PACK OF 72 RETROSPOT CAKE CASES       33386
POPCORN HOLDER                        30492
RABBIT NIGHT LIGHT                    27045
MINI PAINT SET VINTAGE                25880
PACK OF 12 LONDON TISSUES             25305
PACK OF 60 PINK PAISLEY CAKE CASES    24129
Name: Quantity, dtype: int64

### 5. Customer Analysis

In [77]:
#Q12. Who are the top 10 customers by spending?
csv.groupby('CustomerID')['sales'].sum().sort_values(ascending=False).head(10)

CustomerID
14646.0    279489.02
18102.0    256438.49
17450.0    187322.17
14911.0    132458.73
12415.0    123725.45
14156.0    113214.59
17511.0     88125.38
16684.0     65892.08
13694.0     62690.54
15311.0     59284.19
Name: sales, dtype: float64

In [82]:
#Q13. How many orders did each customer place?
customer_orders = (csv.groupby('CustomerID')['InvoiceNo'].nunique().sort_values(ascending=False))
customer_orders

CustomerID
14911.0    248
12748.0    224
17841.0    169
14606.0    128
15311.0    118
          ...
18240.0      1
12378.0      1
18262.0      1
12361.0      1
12357.0      1
Name: InvoiceNo, Length: 4372, dtype: int64

In [83]:
#Q14. Find customers who placed more than 10 orders.
customer_orders[customer_orders>10]

CustomerID
14911.0    248
12748.0    224
17841.0    169
14606.0    128
15311.0    118
          ...
12747.0     11
16767.0     11
17528.0     11
15299.0     11
15059.0     11
Name: InvoiceNo, Length: 459, dtype: int64

In [94]:
#Q15. What is the average spending per customer?
csv.groupby('CustomerID')['sales'].mean()

CustomerID
12346.0     0.000000
12347.0    23.681319
12348.0    57.975484
12349.0    24.076027
12350.0    19.670588
             ...
18280.0    18.060000
18281.0    11.545714
18282.0    13.584615
18283.0     2.837074
18287.0    26.246857
Name: sales, Length: 4372, dtype: float64

In [91]:
customer_spending = csv.groupby('CustomerID')['sales'].sum()

customer_spending.mean()

np.float64(1893.5314327538883)

### 6. Date Analysis

In [111]:
#Q16. What is the total revenue for each month?
csv.groupby(csv['InvoiceDate'].dt.month)['sales'].sum()

InvoiceDate
1      473731.900
2      435534.070
3      578576.210
4      425222.671
5      647011.670
6      606862.520
7      573112.321
8      615078.090
9      929356.232
10     973306.380
11    1126815.070
12     893912.290
Name: sales, dtype: float64

In [112]:
#right approch
monthly_sales = (
    csv.groupby(csv['InvoiceDate'].dt.to_period('M'))['sales'].sum()
)
monthly_sales

InvoiceDate
2010-12     552372.860
2011-01     473731.900
2011-02     435534.070
2011-03     578576.210
2011-04     425222.671
2011-05     647011.670
2011-06     606862.520
2011-07     573112.321
2011-08     615078.090
2011-09     929356.232
2011-10     973306.380
2011-11    1126815.070
2011-12     341539.430
Freq: M, Name: sales, dtype: float64

In [115]:
#Q17. Which month had the highest revenue?
monthly_sales.idxmax()

Period('2011-11', 'M')

In [116]:
monthly_sales.max()

1126815.07

In [117]:
monthly_sales.sort_values(ascending=False).head(1)

InvoiceDate
2011-11    1126815.07
Freq: M, Name: sales, dtype: float64

In [120]:
csv.groupby(csv['InvoiceDate'].dt.day_name())['InvoiceNo'].nunique().sort_values(ascending=False)

InvoiceDate
Thursday     4978
Wednesday    4110
Tuesday      3892
Monday       3512
Friday       3356
Sunday       2342
Name: InvoiceNo, dtype: int64